import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Headers from "./_components/Headers";
import { provider } from "./_components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InstaProp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider className="flex items-center justify-center">
      <html lang="en">
        <head>
          <link
            rel="shortcut icon"
            href="/logo.png"
            // type="image/<generated>"
            // sizes="<generated>"
          />
        </head>
        <body className={inter.className}>
          <provider>
            <Headers />
            {children}
            <footer />
          </provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
